# Array indexing and slicing

# indexing

In [1]:
import numpy as np


In [2]:
arr1=np.array([1,2,3,4,5])

In [3]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr1[0]

1

In [6]:
arr1[1]

2

In [7]:
arr2=np.random.randint(1,10,size=(3,3))

In [8]:
arr2

array([[6, 1, 8],
       [4, 9, 3],
       [5, 2, 6]])

In [10]:
arr2[0][0]

6

In [11]:
arr3=np.random.randint(1,10,size=(2,3,3))

In [12]:
arr3

array([[[9, 3, 5],
        [5, 8, 5],
        [6, 9, 1]],

       [[7, 1, 8],
        [3, 6, 3],
        [8, 2, 1]]])

In [14]:
arr3[0,1,1]

8

# slicing

In [15]:
print(arr1)

[1 2 3 4 5]


In [16]:
arr[0:2]

NameError: name 'arr' is not defined